name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]  # সর্বশেষ স্থিতিশীল Node.js

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'  # dependency cache

    - name: Install dependencies
      run: npm ci || npm install  # যদি ci fail হয়, install try করবে

    - name: Run tests (optional)
      if: exists('package.json')
      run: npm test || echo "No tests defined"

    - name: Start application
      if: exists('package.json')
      run: npm start || echo "No start script defined"
